name: Build & Test CondPredict (Windows exe + outputs)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller catboost pandas numpy

      # ---- ビルド ----
      - name: Build exe with PyInstaller
        run: pyinstaller --onefile --name CondPredict --add-data "app_resources;app_resources" pref2cond_predict2.py

      # ---- 入力を dist/ にコピー ----
      - name: Copy Pref2Cond.csv
        run: copy Pref2Cond.csv dist\Pref2Cond.csv

      # ---- exe 実行（出力CSV生成）----
      - name: Run exe to produce outputs
        working-directory: dist
        run: .\CondPredict.exe

      # ---- 成果物アップロード ----
      - name: Upload exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: CondPredict-exe
          path: dist/CondPredict.exe
          if-no-files-found: error
          retention-days: 14

      - name: Upload run outputs
        uses: actions/upload-artifact@v4
        with:
          name: CondPredict-outputs
          path: |
            dist/Pref2Cond_result_*.csv
            dist/Pref2Cond.csv
          if-no-files-found: warn
          retention-days: 14
